/*
@author: Sideeq
Controller
 */
import sha1 from 'sha1';
import { dbClient } from '../utils/db';
import { redisClient } from '../utils/redis';

class UsersController {
  static async postNew(req, res) {
    // Get the post body from request
    const { email, password } = req.body;

    // check if email and oassword are provided
    if (!email) {
      return res.status(400).json({ error: 'Missing email' });
    }
    if (!password) {
      return res.status(400).json({ error: 'Missing password' });
    }

    // check if email already exists in the database
    const existingUser = await dbClient.usersCollection.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ error: 'Already exists' });
    }

    // Hash the password using SHA1
    const hashedPassword = sha1(password);

    // create a new User
    const newUser = {
      email,
      password: hashedPassword,
    };

    // Insert the new user document into users collection
    const result = await dbClient.usersCollection.insertOne(newUser);

    // Return new user with only email and id autogenerated by Mongodb
    const createdUser = {
      email: result.ops[0].email,
      id: result.insertedId,
    };

    return res.status(201).json(createdUser);
  }

  static async getMe(req, res) {
    // retrieve the token from header
    const token = req.header('X-Token');

    // check if token is valid
    if (!token) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    // get the userId from redisClient via the token as key
    const userId = await redisClient.get(`auth_${token}`);
    if (!userId) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    // get the user from dbCLient using the userId
    const user = await dbClient.usersCollection.findOne({ _id: userId });
    if (!user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    // return the user object (email and id only)
    return res.status(200).json({ email: user.email, id: user._id });
  }
}

export default UsersController;
